-- ********************************** SqlDBM: AlloyDB **********************************
-- * Generated by SqlDBM: AlloyDB Sample, v2 by alexey.alferov+allowdb.demo@sqldbm.com *



-- ************************************** "public".Supplier_copy_1

CREATE TABLE "public".Supplier_copy_1
(
 SupplierId  integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 CompanyName varchar(40) NOT NULL,
 Phone       varchar(20) NULL,
 CONSTRAINT PK_Supplier PRIMARY KEY ( SupplierId ),
 CONSTRAINT AK1_Supplier_CompanyName UNIQUE ( CompanyName )
);

COMMENT ON TABLE "public".Supplier_copy_1 IS 'Basic information 
about Supplier';






-- ************************************** "public".Supplier

CREATE TABLE "public".Supplier
(
 SupplierId  integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 CompanyName varchar(40) NOT NULL,
 Phone       varchar(20) NULL,
 CONSTRAINT PK_Supplier PRIMARY KEY ( SupplierId ),
 CONSTRAINT AK1_Supplier_CompanyName UNIQUE ( CompanyName )
);

COMMENT ON TABLE "public".Supplier IS 'Basic information 
about Supplier';






-- ************************************** "public".Customer_copy_1

CREATE TABLE "public".Customer_copy_1
(
 CustomerId   integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 CustomerName varchar(50) NOT NULL,
 Phone        varchar(20) NULL,
 CONSTRAINT PK_Customer PRIMARY KEY ( CustomerId ),
 CONSTRAINT AK1_Customer_CustomerName UNIQUE ( CustomerName )
);

COMMENT ON TABLE "public".Customer_copy_1 IS 'Basic information 
about Customer';






-- ************************************** "public".Customer

CREATE TABLE "public".Customer
(
 CustomerId   integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 CustomerName varchar(50) NOT NULL,
 Phone        varchar(20) NULL,
 CONSTRAINT PK_Customer PRIMARY KEY ( CustomerId ),
 CONSTRAINT AK1_Customer_CustomerName UNIQUE ( CustomerName )
);

COMMENT ON TABLE "public".Customer IS 'Basic information 
about Customer';






-- ************************************** "public".Product_copy_1

CREATE TABLE "public".Product_copy_1
(
 ProductId      integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 ProductName    varchar(50) NOT NULL,
 SupplierId     integer NOT NULL,
 UnitPrice      decimal(12,2) NULL,
 IsDiscontinued bit NOT NULL DEFAULT ((0)),
 CONSTRAINT PK_Product PRIMARY KEY ( ProductId ),
 CONSTRAINT AK1_Product_SupplierId_ProductName UNIQUE ( ProductName, SupplierId ),
 CONSTRAINT FK_Product_SupplierId_Supplier_copy_1 FOREIGN KEY ( SupplierId ) REFERENCES "public".Supplier_copy_1 ( SupplierId )
);

CREATE INDEX FK_Product_SupplierId_Supplier ON "public".Product_copy_1
(
 SupplierId
);

COMMENT ON TABLE "public".Product_copy_1 IS 'Basic information 
about Product';






-- ************************************** "public".Product

CREATE TABLE "public".Product
(
 ProductId      integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 ProductName    varchar(50) NOT NULL,
 SupplierId     integer NOT NULL,
 UnitPrice      decimal(12,2) NULL,
 IsDiscontinued bit NOT NULL DEFAULT ((0)),
 CONSTRAINT PK_Product PRIMARY KEY ( ProductId ),
 CONSTRAINT AK1_Product_SupplierId_ProductName UNIQUE ( SupplierId, ProductName ),
 CONSTRAINT FK_Product_SupplierId_Supplier FOREIGN KEY ( SupplierId ) REFERENCES "public".Supplier ( SupplierId )
);

CREATE INDEX FK_Product_SupplierId_Supplier ON "public".Product
(
 SupplierId
);

COMMENT ON TABLE "public".Product IS 'Basic information 
about Product';






-- ************************************** "public".Order_copy_1

CREATE TABLE "public".Order_copy_1
(
 OrderId     integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 OrderNumber varchar(10) NULL,
 CustomerId  integer NOT NULL,
 OrderDate   timestamp NOT NULL DEFAULT (getdate()),
 TotalAmount decimal(12,2) NOT NULL,
 CONSTRAINT PK_Order PRIMARY KEY ( OrderId ),
 CONSTRAINT AK1_Order_OrderNumber UNIQUE ( OrderNumber ),
 CONSTRAINT FK_Order_CustomerId_Customer_copy_1 FOREIGN KEY ( CustomerId ) REFERENCES "public".Customer_copy_1 ( CustomerId )
);

CREATE INDEX FK_Order_CustomerId_Customer ON "public".Order_copy_1
(
 CustomerId
);

COMMENT ON TABLE "public".Order_copy_1 IS 'Order information
like Date, Amount';






-- ************************************** "public"."Order"

CREATE TABLE "public"."Order"
(
 OrderId     integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 OrderNumber varchar(10) NULL,
 CustomerId  integer NOT NULL,
 OrderDate   timestamp NOT NULL DEFAULT (getdate()),
 TotalAmount decimal(12,2) NOT NULL,
 CONSTRAINT PK_Order PRIMARY KEY ( OrderId ),
 CONSTRAINT AK1_Order_OrderNumber UNIQUE ( OrderNumber ),
 CONSTRAINT FK_Order_CustomerId_Customer FOREIGN KEY ( CustomerId ) REFERENCES "public".Customer ( CustomerId )
);

CREATE INDEX FK_Order_CustomerId_Customer ON "public"."Order"
(
 CustomerId
);

COMMENT ON TABLE "public"."Order" IS 'Order information
like Date, Amount';






-- ************************************** "public".OrderItem_copy_1

CREATE TABLE "public".OrderItem_copy_1
(
 OrderId   integer NOT NULL,
 ProductId integer NOT NULL,
 UnitPrice decimal(12,2) NOT NULL,
 Quantity  integer NOT NULL,
 CONSTRAINT PK_OrderItem PRIMARY KEY ( OrderId, ProductId ),
 CONSTRAINT FK_OrderItem_OrderId_Order_copy_1 FOREIGN KEY ( OrderId ) REFERENCES "public".Order_copy_1 ( OrderId ),
 CONSTRAINT FK_OrderItem_ProductId_Product_copy_1 FOREIGN KEY ( ProductId ) REFERENCES "public".Product_copy_1 ( ProductId )
);

CREATE INDEX FK_OrderItem_OrderId_Order ON "public".OrderItem_copy_1
(
 OrderId
);

CREATE INDEX FK_OrderItem_ProductId_Product ON "public".OrderItem_copy_1
(
 ProductId
);

COMMENT ON TABLE "public".OrderItem_copy_1 IS 'Information about
like Price, Quantity';






-- ************************************** "public".OrderItem

CREATE TABLE "public".OrderItem
(
 OrderId   integer NOT NULL,
 ProductId integer NOT NULL,
 UnitPrice decimal(12,2) NOT NULL,
 Quantity  integer NOT NULL,
 CONSTRAINT PK_OrderItem PRIMARY KEY ( OrderId, ProductId ),
 CONSTRAINT FK_OrderItem_OrderId_Order FOREIGN KEY ( OrderId ) REFERENCES "public"."Order" ( OrderId ),
 CONSTRAINT FK_OrderItem_ProductId_Product FOREIGN KEY ( ProductId ) REFERENCES "public".Product ( ProductId )
);

CREATE INDEX FK_OrderItem_OrderId_Order ON "public".OrderItem
(
 OrderId
);

CREATE INDEX FK_OrderItem_ProductId_Product ON "public".OrderItem
(
 ProductId
);

COMMENT ON TABLE "public".OrderItem IS 'Information about
like Price, Quantity';





