-- ********************************** SqlDBM: AlloyDB **********************************
-- * Generated by SqlDBM: AlloyDB Sample, v3 by alexey.alferov+allowdb.demo@sqldbm.com *



-- ************************************** table_195_copy_4

CREATE TABLE table_195_copy_4
(
 col_196 inet NULL,
 col_197 int NOT NULL,
 col_198 int4range NOT NULL,
 col_199 int8range NOT NULL,
 col_200 integer NOT NULL,
 col_201 interval NOT NULL,
 col_202 interval NOT NULL,
 col_203 interval NOT NULL,
 col_204 interval NOT NULL,
 col_205 interval NOT NULL,
 col_206 interval NOT NULL,
 col_207 interval NOT NULL,
 col_208 interval NOT NULL,
 col_209 interval NOT NULL,
 col_210 interval NOT NULL,
 col_211 interval NOT NULL,
 col_212 interval NOT NULL,
 col_213 interval NOT NULL,
 col_214 interval NOT NULL,
 col_215 interval NOT NULL,
 col_216 bigint NOT NULL,
 col_217 bigserial NOT NULL,
 col_218 bit NOT NULL,
 col_219 bit (1) NOT NULL,
 col_220 bit NOT NULL,
 col_221 bit NOT NULL

);








-- ************************************** table_195_copy_3

CREATE TABLE table_195_copy_3
(
 col_196 inet NULL,
 col_197 int NOT NULL,
 col_198 int4range NOT NULL,
 col_199 int8range NOT NULL,
 col_200 integer NOT NULL,
 col_201 interval NOT NULL,
 col_202 interval NOT NULL,
 col_203 interval NOT NULL,
 col_204 interval NOT NULL,
 col_205 interval NOT NULL,
 col_206 interval NOT NULL,
 col_207 interval NOT NULL,
 col_208 interval NOT NULL,
 col_209 interval NOT NULL,
 col_210 interval NOT NULL,
 col_211 interval NOT NULL,
 col_212 interval NOT NULL,
 col_213 interval NOT NULL,
 col_214 interval NOT NULL,
 col_215 interval NOT NULL,
 col_216 bigint NOT NULL,
 col_217 bigserial NOT NULL,
 col_218 bit NOT NULL,
 col_219 bit (1) NOT NULL,
 col_220 bit NOT NULL,
 col_221 bit NOT NULL

);








-- ************************************** table_195_copy_2

CREATE TABLE table_195_copy_2
(
 col_196 inet NULL,
 col_197 int NOT NULL,
 col_198 int4range NOT NULL,
 col_199 int8range NOT NULL,
 col_200 integer NOT NULL,
 col_201 interval NOT NULL,
 col_202 interval NOT NULL,
 col_203 interval NOT NULL,
 col_204 interval NOT NULL,
 col_205 interval NOT NULL,
 col_206 interval NOT NULL,
 col_207 interval NOT NULL,
 col_208 interval NOT NULL,
 col_209 interval NOT NULL,
 col_210 interval NOT NULL,
 col_211 interval NOT NULL,
 col_212 interval NOT NULL,
 col_213 interval NOT NULL,
 col_214 interval NOT NULL,
 col_215 interval NOT NULL,
 col_216 bigint NOT NULL,
 col_217 bigserial NOT NULL,
 col_218 bit NOT NULL,
 col_219 bit (1) NOT NULL,
 col_220 bit NOT NULL,
 col_221 bit NOT NULL

);








-- ************************************** table_195_copy_1

CREATE TABLE table_195_copy_1
(
 col_196 inet NULL,
 col_197 int NOT NULL,
 col_198 int4range NOT NULL,
 col_199 int8range NOT NULL,
 col_200 integer NOT NULL,
 col_201 interval NOT NULL,
 col_202 interval NOT NULL,
 col_203 interval NOT NULL,
 col_204 interval NOT NULL,
 col_205 interval NOT NULL,
 col_206 interval NOT NULL,
 col_207 interval NOT NULL,
 col_208 interval NOT NULL,
 col_209 interval NOT NULL,
 col_210 interval NOT NULL,
 col_211 interval NOT NULL,
 col_212 interval NOT NULL,
 col_213 interval NOT NULL,
 col_214 interval NOT NULL,
 col_215 interval NOT NULL,
 col_216 bigint NOT NULL,
 col_217 bigserial NOT NULL,
 col_218 bit NOT NULL,
 col_219 bit (1) NOT NULL,
 col_220 bit NOT NULL,
 col_221 bit NOT NULL

);








-- ************************************** table_195

CREATE TABLE table_195
(
 col_196 inet NULL,
 col_197 int NOT NULL,
 col_198 int4range NOT NULL,
 col_199 int8range NOT NULL,
 col_200 integer NOT NULL,
 col_201 interval NOT NULL,
 col_202 interval NOT NULL,
 col_203 interval NOT NULL,
 col_204 interval NOT NULL,
 col_205 interval NOT NULL,
 col_206 interval NOT NULL,
 col_207 interval NOT NULL,
 col_208 interval NOT NULL,
 col_209 interval NOT NULL,
 col_210 interval NOT NULL,
 col_211 interval NOT NULL,
 col_212 interval NOT NULL,
 col_213 interval NOT NULL,
 col_214 interval NOT NULL,
 col_215 interval NOT NULL,
 col_216 bigint NOT NULL,
 col_217 bigserial NOT NULL,
 col_218 bit NOT NULL,
 col_219 bit (1) NOT NULL,
 col_220 bit NOT NULL,
 col_221 bit NOT NULL

);








-- ************************************** table_137

CREATE TABLE table_137
(

);








-- ************************************** table_136

CREATE TABLE table_136
(

);








-- ************************************** table_135

CREATE TABLE table_135
(

);








-- ************************************** table_134

CREATE TABLE table_134
(

);








-- ************************************** table_133

CREATE TABLE table_133
(

);








-- ************************************** table_132

CREATE TABLE table_132
(

);








-- ************************************** table_131

CREATE TABLE table_131
(

);








-- ************************************** "public".Supplier_copy_1

CREATE TABLE "public".Supplier_copy_1
(
 SupplierId  integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 CompanyName varchar(40) NOT NULL,
 Phone       varchar(20) NULL,
 CONSTRAINT PK_Supplier PRIMARY KEY ( SupplierId ),
 CONSTRAINT AK1_Supplier_CompanyName UNIQUE ( CompanyName )
);

COMMENT ON TABLE "public".Supplier_copy_1 IS 'Basic information 
about Supplier';






-- ************************************** "public".Supplier

CREATE TABLE "public".Supplier
(
 SupplierId  integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 CompanyName varchar(40) NOT NULL,
 Phone       varchar(20) NULL,
 CONSTRAINT PK_Supplier PRIMARY KEY ( SupplierId ),
 CONSTRAINT AK1_Supplier_CompanyName UNIQUE ( CompanyName )
);

COMMENT ON TABLE "public".Supplier IS 'Basic information 
about Supplier';






-- ************************************** "public".Customer_copy_1

CREATE TABLE "public".Customer_copy_1
(
 CustomerId   integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 CustomerName varchar(50) NOT NULL,
 Phone        varchar(20) NULL,
 CONSTRAINT PK_Customer PRIMARY KEY ( CustomerId ),
 CONSTRAINT AK1_Customer_CustomerName UNIQUE ( CustomerName )
);

COMMENT ON TABLE "public".Customer_copy_1 IS 'Basic information 
about Customer';






-- ************************************** "public".Customer

CREATE TABLE "public".Customer
(
 CustomerId   integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 CustomerName varchar(50) NOT NULL,
 Phone        varchar(20) NULL,
 CONSTRAINT PK_Customer PRIMARY KEY ( CustomerId ),
 CONSTRAINT AK1_Customer_CustomerName UNIQUE ( CustomerName )
);

COMMENT ON TABLE "public".Customer IS 'Basic information 
about Customer';






-- ************************************** "public".Product_copy_1

CREATE TABLE "public".Product_copy_1
(
 ProductId      integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 ProductName    varchar(50) NOT NULL,
 SupplierId     integer NOT NULL,
 UnitPrice      decimal(12,2) NULL,
 IsDiscontinued bit NOT NULL DEFAULT ((0)),
 CONSTRAINT PK_Product PRIMARY KEY ( ProductId ),
 CONSTRAINT AK1_Product_SupplierId_ProductName UNIQUE ( ProductName, SupplierId ),
 CONSTRAINT FK_Product_SupplierId_Supplier_copy_1 FOREIGN KEY ( SupplierId ) REFERENCES "public".Supplier_copy_1 ( SupplierId )
);

CREATE INDEX FK_Product_SupplierId_Supplier ON "public".Product_copy_1
(
 SupplierId
);

COMMENT ON TABLE "public".Product_copy_1 IS 'Basic information 
about Product';






-- ************************************** "public".Product

CREATE TABLE "public".Product
(
 ProductId      integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 ProductName    varchar(50) NOT NULL,
 SupplierId     integer NOT NULL,
 UnitPrice      decimal(12,2) NULL,
 IsDiscontinued bit NOT NULL DEFAULT ((0)),
 CONSTRAINT PK_Product PRIMARY KEY ( ProductId ),
 CONSTRAINT AK1_Product_SupplierId_ProductName UNIQUE ( SupplierId, ProductName ),
 CONSTRAINT FK_Product_SupplierId_Supplier FOREIGN KEY ( SupplierId ) REFERENCES "public".Supplier ( SupplierId ),
 CONSTRAINT check_252 CHECK ( 1 ) NO INHERIT NOT VALID
);

CREATE INDEX FK_Product_SupplierId_Supplier ON "public".Product
(
 SupplierId
);

COMMENT ON TABLE "public".Product IS 'Basic information 
about Product';






-- ************************************** "public".Order_copy_1

CREATE TABLE "public".Order_copy_1
(
 OrderId     integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 OrderNumber varchar(10) NULL,
 CustomerId  integer NOT NULL,
 OrderDate   timestamp NOT NULL DEFAULT (getdate()),
 TotalAmount decimal(12,2) NOT NULL,
 CONSTRAINT PK_Order PRIMARY KEY ( OrderId ),
 CONSTRAINT AK1_Order_OrderNumber UNIQUE ( OrderNumber ),
 CONSTRAINT FK_Order_CustomerId_Customer_copy_1 FOREIGN KEY ( CustomerId ) REFERENCES "public".Customer_copy_1 ( CustomerId )
);

CREATE INDEX FK_Order_CustomerId_Customer ON "public".Order_copy_1
(
 CustomerId
);

COMMENT ON TABLE "public".Order_copy_1 IS 'Order information
like Date, Amount';






-- ************************************** "public"."Order"

CREATE TABLE "public"."Order"
(
 OrderId     integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 OrderNumber varchar(10) NULL,
 CustomerId  integer NOT NULL,
 OrderDate   timestamp NOT NULL DEFAULT (getdate()),
 TotalAmount decimal(12,2) NOT NULL,
 CONSTRAINT PK_Order PRIMARY KEY ( OrderId ),
 CONSTRAINT AK1_Order_OrderNumber UNIQUE ( OrderNumber ),
 CONSTRAINT FK_Order_CustomerId_Customer FOREIGN KEY ( CustomerId ) REFERENCES "public".Customer ( CustomerId )
);

CREATE INDEX FK_Order_CustomerId_Customer ON "public"."Order"
(
 CustomerId
);

COMMENT ON TABLE "public"."Order" IS 'Order information
like Date, Amount';






-- ************************************** "public".OrderItem_copy_1

CREATE TABLE "public".OrderItem_copy_1
(
 OrderId   integer NOT NULL,
 ProductId integer NOT NULL,
 UnitPrice decimal(12,2) NOT NULL,
 Quantity  integer NOT NULL,
 CONSTRAINT PK_OrderItem PRIMARY KEY ( OrderId, ProductId ),
 CONSTRAINT FK_OrderItem_OrderId_Order_copy_1 FOREIGN KEY ( OrderId ) REFERENCES "public".Order_copy_1 ( OrderId ),
 CONSTRAINT FK_OrderItem_ProductId_Product_copy_1 FOREIGN KEY ( ProductId ) REFERENCES "public".Product_copy_1 ( ProductId )
);

CREATE INDEX FK_OrderItem_OrderId_Order ON "public".OrderItem_copy_1
(
 OrderId
);

CREATE INDEX FK_OrderItem_ProductId_Product ON "public".OrderItem_copy_1
(
 ProductId
);

COMMENT ON TABLE "public".OrderItem_copy_1 IS 'Information about
like Price, Quantity';






-- ************************************** "public".OrderItem

CREATE TABLE "public".OrderItem
(
 OrderId   integer NOT NULL,
 ProductId integer NOT NULL,
 UnitPrice decimal(12,2) NOT NULL,
 Quantity  integer NOT NULL,
 CONSTRAINT PK_OrderItem PRIMARY KEY ( OrderId, ProductId ),
 CONSTRAINT FK_OrderItem_OrderId_Order FOREIGN KEY ( OrderId ) REFERENCES "public"."Order" ( OrderId ),
 CONSTRAINT FK_OrderItem_ProductId_Product FOREIGN KEY ( ProductId ) REFERENCES "public".Product ( ProductId )
);

CREATE INDEX FK_OrderItem_OrderId_Order ON "public".OrderItem
(
 OrderId
);

CREATE INDEX FK_OrderItem_ProductId_Product ON "public".OrderItem
(
 ProductId
);

COMMENT ON TABLE "public".OrderItem IS 'Information about
like Price, Quantity';





