-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************



-- ************************************** "public".OrderItem_copy_1

CREATE TABLE "public".OrderItem_copy_1
(
 OrderId   integer NOT NULL,
 ProductId integer NOT NULL,
 UnitPrice decimal(12,2) NOT NULL,
 Quantity  integer NOT NULL,
 CONSTRAINT PK_OrderItem PRIMARY KEY ( OrderId, ProductId ),
 CONSTRAINT FK_OrderItem_OrderId_Order_copy_1 FOREIGN KEY ( OrderId ) REFERENCES "public".Order_copy_1 ( OrderId ),
 CONSTRAINT FK_OrderItem_ProductId_Product_copy_1 FOREIGN KEY ( ProductId ) REFERENCES "public".Product_copy_1 ( ProductId )
);

CREATE INDEX FK_OrderItem_OrderId_Order ON "public".OrderItem_copy_1
(
 OrderId
);

CREATE INDEX FK_OrderItem_ProductId_Product ON "public".OrderItem_copy_1
(
 ProductId
);

COMMENT ON TABLE "public".OrderItem_copy_1 IS 'Information about
like Price, Quantity';




