-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************



-- ************************************** "public".Product_copy_1

CREATE TABLE "public".Product_copy_1
(
 ProductId      integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 ProductName    varchar(50) NOT NULL,
 SupplierId     integer NOT NULL,
 UnitPrice      decimal(12,2) NULL,
 IsDiscontinued bit NOT NULL DEFAULT ((0)),
 CONSTRAINT PK_Product PRIMARY KEY ( ProductId ),
 CONSTRAINT AK1_Product_SupplierId_ProductName UNIQUE ( ProductName, SupplierId ),
 CONSTRAINT FK_Product_SupplierId_Supplier_copy_1 FOREIGN KEY ( SupplierId ) REFERENCES "public".Supplier_copy_1 ( SupplierId )
);

CREATE INDEX FK_Product_SupplierId_Supplier ON "public".Product_copy_1
(
 SupplierId
);

COMMENT ON TABLE "public".Product_copy_1 IS 'Basic information 
about Product';




