-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************



-- ************************************** "public".OrderItem

CREATE TABLE "public".OrderItem
(
 OrderId   integer NOT NULL,
 ProductId integer NOT NULL,
 UnitPrice decimal(12,2) NOT NULL,
 Quantity  integer NOT NULL,
 CONSTRAINT PK_OrderItem PRIMARY KEY ( OrderId, ProductId ),
 CONSTRAINT FK_OrderItem_OrderId_Order FOREIGN KEY ( OrderId ) REFERENCES "public"."Order" ( OrderId ),
 CONSTRAINT FK_OrderItem_ProductId_Product FOREIGN KEY ( ProductId ) REFERENCES "public".Product ( ProductId )
);

CREATE INDEX FK_OrderItem_OrderId_Order ON "public".OrderItem
(
 OrderId
);

CREATE INDEX FK_OrderItem_ProductId_Product ON "public".OrderItem
(
 ProductId
);

COMMENT ON TABLE "public".OrderItem IS 'Information about
like Price, Quantity';




