-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************



-- ************************************** "public".Customer_copy_1

CREATE TABLE "public".Customer_copy_1
(
 CustomerId   integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 CustomerName varchar(50) NOT NULL,
 Phone        varchar(20) NULL,
 CONSTRAINT PK_Customer PRIMARY KEY ( CustomerId ),
 CONSTRAINT AK1_Customer_CustomerName UNIQUE ( CustomerName )
);

COMMENT ON TABLE "public".Customer_copy_1 IS 'Basic information 
about Customer';




