-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************



-- ************************************** "public".Order_copy_1

CREATE TABLE "public".Order_copy_1
(
 OrderId     integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 OrderNumber varchar(10) NULL,
 CustomerId  integer NOT NULL,
 OrderDate   timestamp NOT NULL DEFAULT (getdate()),
 TotalAmount decimal(12,2) NOT NULL,
 CONSTRAINT PK_Order PRIMARY KEY ( OrderId ),
 CONSTRAINT AK1_Order_OrderNumber UNIQUE ( OrderNumber ),
 CONSTRAINT FK_Order_CustomerId_Customer_copy_1 FOREIGN KEY ( CustomerId ) REFERENCES "public".Customer_copy_1 ( CustomerId )
);

CREATE INDEX FK_Order_CustomerId_Customer ON "public".Order_copy_1
(
 CustomerId
);

COMMENT ON TABLE "public".Order_copy_1 IS 'Order information
like Date, Amount';




