-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************



-- ************************************** "public".Supplier

CREATE TABLE "public".Supplier
(
 SupplierId  integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 CompanyName varchar(40) NOT NULL,
 Phone       varchar(20) NULL,
 CONSTRAINT PK_Supplier PRIMARY KEY ( SupplierId ),
 CONSTRAINT AK1_Supplier_CompanyName UNIQUE ( CompanyName )
);

COMMENT ON TABLE "public".Supplier IS 'Basic information 
about Supplier';




