-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************



-- ************************************** "public".Customer

CREATE TABLE "public".Customer
(
 CustomerId   integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 CustomerName varchar(50) NOT NULL,
 Phone        varchar(20) NULL,
 CONSTRAINT PK_Customer PRIMARY KEY ( CustomerId ),
 CONSTRAINT AK1_Customer_CustomerName UNIQUE ( CustomerName )
);

COMMENT ON TABLE "public".Customer IS 'Basic information 
about Customer';




