-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************



-- ************************************** "public".Product

CREATE TABLE "public".Product
(
 ProductId      integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 ProductName    varchar(50) NOT NULL,
 SupplierId     integer NOT NULL,
 UnitPrice      decimal(12,2) NULL,
 IsDiscontinued bit NOT NULL DEFAULT ((0)),
 CONSTRAINT PK_Product PRIMARY KEY ( ProductId ),
 CONSTRAINT AK1_Product_SupplierId_ProductName UNIQUE ( SupplierId, ProductName ),
 CONSTRAINT FK_Product_SupplierId_Supplier FOREIGN KEY ( SupplierId ) REFERENCES "public".Supplier ( SupplierId )
);

CREATE INDEX FK_Product_SupplierId_Supplier ON "public".Product
(
 SupplierId
);

COMMENT ON TABLE "public".Product IS 'Basic information 
about Product';




