-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************



-- ************************************** "public"."Order"

CREATE TABLE "public"."Order"
(
 OrderId     integer NOT NULL GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 OrderNumber varchar(10) NULL,
 CustomerId  integer NOT NULL,
 OrderDate   timestamp NOT NULL DEFAULT (getdate()),
 TotalAmount decimal(12,2) NOT NULL,
 CONSTRAINT PK_Order PRIMARY KEY ( OrderId ),
 CONSTRAINT AK1_Order_OrderNumber UNIQUE ( OrderNumber ),
 CONSTRAINT FK_Order_CustomerId_Customer FOREIGN KEY ( CustomerId ) REFERENCES "public".Customer ( CustomerId )
);

CREATE INDEX FK_Order_CustomerId_Customer ON "public"."Order"
(
 CustomerId
);

COMMENT ON TABLE "public"."Order" IS 'Order information
like Date, Amount';




