-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************



-- ************************************** table_195

CREATE TABLE table_195
(
 col_196 inet NULL,
 col_197 int NOT NULL,
 col_198 int4range NOT NULL,
 col_199 int8range NOT NULL,
 col_200 integer NOT NULL,
 col_201 interval NOT NULL,
 col_202 interval NOT NULL,
 col_203 interval NOT NULL,
 col_204 interval NOT NULL,
 col_205 interval NOT NULL,
 col_206 interval NOT NULL,
 col_207 interval NOT NULL,
 col_208 interval NOT NULL,
 col_209 interval NOT NULL,
 col_210 interval NOT NULL,
 col_211 interval NOT NULL,
 col_212 interval NOT NULL,
 col_213 interval NOT NULL,
 col_214 interval NOT NULL,
 col_215 interval NOT NULL,
 col_216 bigint NOT NULL,
 col_217 bigserial NOT NULL,
 col_218 bit NOT NULL,
 col_219 bit (1) NOT NULL,
 col_220 bit NOT NULL,
 col_221 bit NOT NULL

);






